services:
  dimadb:
    build:
      context: .
      dockerfile: dockerfile
    image: dimadb:latest
    container_name: dimadb
    restart: unless-stopped
    environment:
      PORT: 80
      PUBLIC_DIR: /app/public
      DATA_DIR: /data
      DIMADB_REDIS_DRAGONFLY: ${DIMADB_REDIS_DRAGONFLY:-redis://dragonfly:6379}
      DIMADB_MONGO_DIMABOT: ${DIMADB_MONGO_DIMABOT:-}
    volumes:
      - ./data:/data
    networks:
      - web-proxy
      - databases

networks:
  web-proxy:
    external: true
  databases:
    external: true
