services:
  dimabot-site:
    image: nginx:alpine
    container_name: dimabot-site
    restart: unless-stopped
    volumes:
      - ./dist/dimasite/browser:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"
    networks:
      - web-proxy

networks:
  web-proxy:
    external: true
