services:
  dimadocs:
    image: nginx:alpine
    container_name: dimadocs
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"
    networks:
      - web-proxy

networks:
  web-proxy:
    external: true
